version: '3.7'

services:
  app:
    image: app:${SERVICE_IMAGE_TAG}
    container_name: app
    restart: ${RESTART_POLICY}
    environment:
      - TZ
      - SERVER_PORT
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}